[package]
name = "arb-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
yellowstone-grpc-client = "13.3"
yellowstone-grpc-proto = "12.7"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
bs58 = "0.5.1"
dotenvy = "0.15.7"
solana-pubkey = { version = "4.3", features = ["curve25519"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
orca_whirlpools_core = "2.1.1"
solana-clmm-raydium = "0.3.0"
solana-keypair = "4.0.0"
solana-signer = "4.0.0"
solana-message = { version = "5.1.0", features = ["wincode"] }
solana-instruction = "4.0.0"
solana-hash = "4.7.0"
